### ISSUE TITLE
Support for Expanded Equivalence support mods, Charset, Mekansim and TConstruct

### ISSUE THREAD

**Issue by pupnewfster** [TagnumElite/ProjectE-Integration#1]
It would be nice to be able to switch from expanded equivalence to this. The biggest issue is that some of the mods that I use are not yet supported.

Are you planning on adding support to all the mods that Expanded Equivalence supports (including the ones I didn't even bother listing as I don't use), or not.

### Todo:
- [x] Actually Additions
- [x] Applied Energistics 2
- [x] Astral Sorcery 
- [x] Avaritia
- [x] Botania
- [x] Compact Machines
- [x] Draconic Evolution
- [x] Embers
- [x] Ender IO
- [x] Forestry
- [x] Immersive Engineering
- [x] Industrial Craft
- [x] Mystical Agriculture
- [x] RebornCore (Tech Reborn)
- [x] Thaumcraft
- [x] Thermal Expansion

- ~~Buildcraft~~ Skipping this for now!

It also would be interesting to see support for these mods.
### Suggestions:
- [x] Charset/Complex Logic (they have their recipes in their own class so it can't be parsed by ProjectE (even though they are more or less normal crafting recipes))
- [x] Mekanism (I know the NBT stuff isn't possible but at least having the machines supported so it knows how to factor in the stuff for alloys)
- [x] Tinkers Construct alloying

**Comment by TagnumElite** [comment]
I am planning to add all support from Expanded Equivalence. I had Mekanism on my radar as well.

Tinkers Construct will be interesting as I don't know how the Fluids work in ProjectE.
Charset/Complex Logic I have never used, but I should be able to add support for.

**Comment by pupnewfster** [comment]
If I remember correctly fluids *do* have an EMC value or at least there are tests for it. https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/test/java/moze_intel/projecte/emc/GraphMapperTest.java#L396

(And it is sort of manageable via the custom conversions files and using `FAKE|`. So even if it has to be more faked, it is possible with tinkers to get how much a material melts down into, (put that into the "emc value" and then have a mapper for the alloy recipes, and then again from what that can be "cast" into in the casting table/basin.
